// DO NOT MANUALLY EDIT THIS FILE. IT IS GENERATED  & OVERWRITTEN BY [ pnpm theme ]

export const GEN_THEME_VAR_NAMES__demo__basic_theme = [
	"owo",
	"background",
	"foreground",
	"muted",
	"muted-foreground",
	"popover",
	"popover-foreground",
	"card",
	"card-foreground",
	"border",
	"input",
	"primary",
	"primary-foreground",
	"secondary",
	"secondary-foreground",
	"accent",
	"destructive",
	"destructive-foreground",
	"ring",
	"owo",
	"background",
	"foreground",
	"muted",
	"muted-foreground",
	"popover",
	"popover-foreground",
	"card",
	"card-foreground",
	"border",
	"input",
	"primary",
	"primary-foreground",
	"secondary",
	"secondary-foreground",
	"accent",
	"destructive",
	"destructive-foreground",
	"ring",
] as const

export default GEN_THEME_VAR_NAMES__demo__basic_theme
