// DO NOT MANUALLY EDIT THIS FILE. IT IS GENERATED  & OVERWRITTEN BY [ pnpm theme ]

export const GEN_THEME__demo__basic_theme = {
	__DU: "tw-theme-app",
	packageJsonName: null,
	colors: {
		owo: {
			type: "color",
			subType: "hsl",
			twName: "owo",
			valueLight: "0deg 0% 98%",
			valueDark: "240deg 10% 4%",
			cssName: "--owo",
			cssNameDark: "--dm-owo",
			cssNameLight: "--lm-owo",
			cssNameVarDark: "var(--dm-owo)",
			cssNameVarLight: "var(--lm-owo)",
		},
		background: {
			type: "color",
			subType: "hsl",
			twName: "background",
			valueLight: "0deg 0% 98%",
			valueDark: "240deg 10% 4%",
			cssName: "--background",
			cssNameDark: "--dm-background",
			cssNameLight: "--lm-background",
			cssNameVarDark: "var(--dm-background)",
			cssNameVarLight: "var(--lm-background)",
		},
		foreground: {
			type: "color",
			subType: "hsl",
			twName: "foreground",
			valueLight: "240deg 10% 4%",
			valueDark: "0deg 0% 98%",
			cssName: "--foreground",
			cssNameDark: "--dm-foreground",
			cssNameLight: "--lm-foreground",
			cssNameVarDark: "var(--dm-foreground)",
			cssNameVarLight: "var(--lm-foreground)",
		},
		muted: {
			type: "color",
			subType: "hsl",
			twName: "muted",
			valueLight: "240deg 5% 96%",
			valueDark: "240deg 4% 16%",
			cssName: "--muted",
			cssNameDark: "--dm-muted",
			cssNameLight: "--lm-muted",
			cssNameVarDark: "var(--dm-muted)",
			cssNameVarLight: "var(--lm-muted)",
		},
		"muted-foreground": {
			type: "color",
			subType: "hsl",
			twName: "muted-foreground",
			valueLight: "240deg 4% 46%",
			valueDark: "240deg 5% 65%",
			cssName: "--muted-foreground",
			cssNameDark: "--dm-muted-foreground",
			cssNameLight: "--lm-muted-foreground",
			cssNameVarDark: "var(--dm-muted-foreground)",
			cssNameVarLight: "var(--lm-muted-foreground)",
		},
		popover: {
			type: "color",
			subType: "hsl",
			twName: "popover",
			valueLight: "0deg 0% 100%",
			valueDark: "240deg 10% 4%",
			cssName: "--popover",
			cssNameDark: "--dm-popover",
			cssNameLight: "--lm-popover",
			cssNameVarDark: "var(--dm-popover)",
			cssNameVarLight: "var(--lm-popover)",
		},
		"popover-foreground": {
			type: "color",
			subType: "hsl",
			twName: "popover-foreground",
			valueLight: "240deg 10% 4%",
			valueDark: "0deg 0% 98%",
			cssName: "--popover-foreground",
			cssNameDark: "--dm-popover-foreground",
			cssNameLight: "--lm-popover-foreground",
			cssNameVarDark: "var(--dm-popover-foreground)",
			cssNameVarLight: "var(--lm-popover-foreground)",
		},
		card: {
			type: "color",
			subType: "hsl",
			twName: "card",
			valueLight: "0deg 0% 100%",
			valueDark: "240deg 10% 4%",
			cssName: "--card",
			cssNameDark: "--dm-card",
			cssNameLight: "--lm-card",
			cssNameVarDark: "var(--dm-card)",
			cssNameVarLight: "var(--lm-card)",
		},
		"card-foreground": {
			type: "color",
			subType: "hsl",
			twName: "card-foreground",
			valueLight: "240deg 10% 4%",
			valueDark: "0deg 0% 98%",
			cssName: "--card-foreground",
			cssNameDark: "--dm-card-foreground",
			cssNameLight: "--lm-card-foreground",
			cssNameVarDark: "var(--dm-card-foreground)",
			cssNameVarLight: "var(--lm-card-foreground)",
		},
		border: {
			type: "color",
			subType: "hsl",
			twName: "border",
			valueLight: "240deg 6% 90%",
			valueDark: "240deg 4% 16%",
			cssName: "--border",
			cssNameDark: "--dm-border",
			cssNameLight: "--lm-border",
			cssNameVarDark: "var(--dm-border)",
			cssNameVarLight: "var(--lm-border)",
		},
		input: {
			type: "color",
			subType: "hsl",
			twName: "input",
			valueLight: "240deg 6% 90%",
			valueDark: "240deg 4% 16%",
			cssName: "--input",
			cssNameDark: "--dm-input",
			cssNameLight: "--lm-input",
			cssNameVarDark: "var(--dm-input)",
			cssNameVarLight: "var(--lm-input)",
		},
		primary: {
			type: "color",
			subType: "hsl",
			twName: "primary",
			valueLight: "240deg 6% 10%",
			valueDark: "0deg 0% 98%",
			cssName: "--primary",
			cssNameDark: "--dm-primary",
			cssNameLight: "--lm-primary",
			cssNameVarDark: "var(--dm-primary)",
			cssNameVarLight: "var(--lm-primary)",
		},
		"primary-foreground": {
			type: "color",
			subType: "hsl",
			twName: "primary-foreground",
			valueLight: "0deg 0% 98%",
			valueDark: "240deg 6% 10%",
			cssName: "--primary-foreground",
			cssNameDark: "--dm-primary-foreground",
			cssNameLight: "--lm-primary-foreground",
			cssNameVarDark: "var(--dm-primary-foreground)",
			cssNameVarLight: "var(--lm-primary-foreground)",
		},
		secondary: {
			type: "color",
			subType: "hsl",
			twName: "secondary",
			valueLight: "240deg 5% 96%",
			valueDark: "240deg 4% 16%",
			cssName: "--secondary",
			cssNameDark: "--dm-secondary",
			cssNameLight: "--lm-secondary",
			cssNameVarDark: "var(--dm-secondary)",
			cssNameVarLight: "var(--lm-secondary)",
		},
		"secondary-foreground": {
			type: "color",
			subType: "hsl",
			twName: "secondary-foreground",
			valueLight: "240deg 6% 10%",
			valueDark: "0deg 0% 98%",
			cssName: "--secondary-foreground",
			cssNameDark: "--dm-secondary-foreground",
			cssNameLight: "--lm-secondary-foreground",
			cssNameVarDark: "var(--dm-secondary-foreground)",
			cssNameVarLight: "var(--lm-secondary-foreground)",
		},
		accent: {
			type: "color",
			subType: "hsl",
			twName: "accent",
			valueLight: "243deg 100% 96%",
			valueDark: "240deg 3% 15%",
			cssName: "--accent",
			cssNameDark: "--dm-accent",
			cssNameLight: "--lm-accent",
			cssNameVarDark: "var(--dm-accent)",
			cssNameVarLight: "var(--lm-accent)",
		},
		destructive: {
			type: "color",
			subType: "hsl",
			twName: "destructive",
			valueLight: "0deg 84% 60%",
			valueDark: "0deg 84% 60%",
			cssName: "--destructive",
			cssNameDark: "--dm-destructive",
			cssNameLight: "--lm-destructive",
			cssNameVarDark: "var(--dm-destructive)",
			cssNameVarLight: "var(--lm-destructive)",
		},
		"destructive-foreground": {
			type: "color",
			subType: "hsl",
			twName: "destructive-foreground",
			valueLight: "0deg 0% 98%",
			valueDark: "0deg 86% 97%",
			cssName: "--destructive-foreground",
			cssNameDark: "--dm-destructive-foreground",
			cssNameLight: "--lm-destructive-foreground",
			cssNameVarDark: "var(--dm-destructive-foreground)",
			cssNameVarLight: "var(--lm-destructive-foreground)",
		},
		ring: {
			type: "color",
			subType: "hsl",
			twName: "ring",
			valueLight: "240deg 5% 65%",
			valueDark: "240deg 4% 16%",
			cssName: "--ring",
			cssNameDark: "--dm-ring",
			cssNameLight: "--lm-ring",
			cssNameVarDark: "var(--dm-ring)",
			cssNameVarLight: "var(--lm-ring)",
		},
	},
	fonts: {
		heading: {
			type: "font",
			twName: "heading",
			valueLight: "unknown",
			valueDark: "unknown",
			cssName: "--font-heading",
			cssNameDark: "--dm-font-heading",
			cssNameLight: "--lm-font-heading",
			cssNameVarDark: "var(--dm-font-heading)",
			cssNameVarLight: "var(--lm-font-heading)",
		},
	},
} as const

export default GEN_THEME__demo__basic_theme
